### ISSUE TITLE
Records associated with same coordinates not showing

### ISSUE THREAD

**Issue by thegsi** [britishlibrary/peripleo#1]
Where several records are associated with the same coordinates, (size of marker changed) only the first three records are displayed. eg on https://britishlibrary.github.io/peripleo-lanc/hfa_exeter/#/?/?/?/mode=points there are 239 BL records but far fewer points on map.  Tool tip always shows '+1 more' could this be updated please? Thanks.

**Comment by rsimon** [comment]
Hi @thegsi,

sorry, completely forgot about this ticket (but not the bug of course!). It's been fixed in one of the recent updates.

Cheers,
Rainer
